---
version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redislabs/redisearch:latest
    ports:
      - "6379:6379"
